import type { Metadata } from 'next';
import Link from 'next/link';
import LegalLayout from '@/components/LegalLayout';

export const metadata: Metadata = { title: 'Terms of Service | FirstCareerSteps', description: 'Terms for using FirstCareerSteps, including AI assistance, account privacy, payments and deletion.' };

export default function TermsPage() {
  return <LegalLayout title="Terms of Service">
    <section><h2>Our service and these terms</h2><p>Pathfinders Ventures LLC, based in Columbus, Ohio, operates FirstCareerSteps.com. These terms govern your use of our resume, professional-profile and career-planning tools. By creating an account or using the service, you agree to these terms. Our <Link href="/privacy">Privacy Policy</Link> explains how information is handled. Questions can be sent to <a href="mailto:brenenmorsecorp@gmail.com?subject=FirstCareerSteps%20support">brenenmorsecorp@gmail.com</a>.</p></section>
    <section><h2>Eligibility and your account</h2><p>You must be at least 13, or the higher minimum age required where you live. If you are under 18, you need a parent or legal guardian&apos;s permission. Keep your sign-in details secure, provide accurate account information, and use only an account you are authorized to access. Notify us of suspected unauthorized access. Schools and educators are responsible for obtaining approvals required for their students&apos; use.</p></section>
    <section><h2>AI assistance is provided through OpenAI</h2><p>Our AI features use the OpenAI API. The relevant information in your request is sent to OpenAI as described in the Privacy Policy. AI output may be wrong, incomplete, biased or similar to output given to other users. Review every suggestion. Do not invent qualifications, employment, education, achievements, references or experience, and do not submit false information to an employer.</p><p>The service provides drafting and general career-planning assistance, not professional legal, financial or employment advice. We do not guarantee an interview, job, school admission, accurate job-market prediction or other outcome. You are responsible for the final content you use.</p></section>
    <section><h2>Your content and privacy</h2><p>You retain your rights in the information and materials you provide. You authorize us and our service providers to process that content as needed to provide and secure the service, generate requested suggestions, save your work and fulfill your instructions. This is not permission to publish your student profile or sell it for advertising.</p><p>Saved profiles and resumes are private within your account, with limited operational access as described in the Privacy Policy. You choose whether to share a downloaded resume or copy content to another service. Do not upload someone else&apos;s private information or material you do not have permission to use.</p></section>
    <section><h2>Acceptable use</h2><p>Do not use the service to impersonate someone, harass others, submit unlawful content, create deceptive applications, attempt to access another account, defeat security controls, or disrupt the service. Do not upload malicious software or use automated requests to abuse the tools. We may restrict or suspend access to investigate misuse, protect users or comply with law.</p></section>
    <section><h2>Subscriptions and payments</h2><p>You may build and preview a resume before purchasing. The current standard PDF-download subscription is $1.99 per year, billed annually in U.S. dollars through Stripe. The price, applicable taxes, features and renewal terms shown at checkout apply to your purchase. Unless canceled, an annual subscription renews and the payment method is charged for the next period.</p><p>Deleting your account cancels future FirstCareerSteps renewals and ends access to saved work. You may also contact us about cancellation before your next renewal. Previously paid amounts are not automatically refunded on deletion; contact us about billing errors or refund requests. Nothing in these terms limits refunds or cancellation rights required by applicable law. We will provide notice of price or renewal changes when required.</p></section>
    <section><h2>Deleting or closing an account</h2><p>You can delete your account in <Link href="/dashboard/settings">Account Settings</Link> after a recent sign-in and explicit confirmation. Download anything you need first. Deletion permanently removes the account and associated saved content after required cleanup succeeds. Limited retained records and third-party copies are explained in the Privacy Policy. If deletion cannot finish, the website will report an error and provide a retry or contact route.</p></section>
    <section><h2>Third-party services</h2><p>LinkedIn setup is optional. FirstCareerSteps does not automatically publish your content to LinkedIn and is not affiliated with or endorsed by LinkedIn, a school or an employer unless expressly stated. Third-party websites, videos and services have their own terms, age requirements and privacy practices. You are responsible for deciding whether to use them.</p></section>
    <section><h2>Availability and responsibility</h2><p>We aim to provide a useful service, but features may change, errors can occur and uninterrupted availability is not guaranteed. To the extent permitted by law, the service and AI suggestions are provided as available without a guarantee that they will meet every purpose. We remain responsible for obligations that cannot lawfully be excluded, and nothing in these terms waives mandatory consumer rights.</p></section>
    <section><h2>Changes and questions</h2><p>We may update these terms as the service changes. The effective date identifies the current version, and we will provide additional notice when required. Contact Pathfinders Ventures LLC using the email above to raise a concern, request support or discuss an account or payment issue.</p></section>
  </LegalLayout>;
}
