import type { Metadata } from 'next';
import Link from 'next/link';
import LegalLayout from '@/components/LegalLayout';

export const metadata: Metadata = { title: 'Privacy Policy | FirstCareerSteps', description: 'How FirstCareerSteps handles student information, AI requests, private profiles, and account deletion.' };

export default function PrivacyPage() {
  return <LegalLayout title="Privacy Policy">
    <section><h2>Who operates FirstCareerSteps</h2><p>FirstCareerSteps is operated by Pathfinders Ventures LLC in Columbus, Ohio. This policy covers FirstCareerSteps.com and its resume, professional-profile and career-planning tools. For privacy questions, access or deletion requests, contact <a href="mailto:brenenmorsecorp@gmail.com?subject=FirstCareerSteps%20privacy">brenenmorsecorp@gmail.com</a>. We may need to verify your identity or authority before releasing or deleting information.</p></section>
    <section><h2>Information we handle</h2><p>We handle your account information, such as name and email; the school, activities, work experience, skills, contact details, photos and other content you choose to enter; generated suggestions, saved resumes and career roadmaps; and payment and subscription status. Stripe processes payment details. Our application does not store full payment-card numbers.</p><p>Our service providers also process technical information needed to run and secure the service, such as IP addresses, browser information, request logs and authentication cookies. We use a first-party campaign cookie for up to 30 days to understand which referral links lead to purchases. Campaign labels may be attached to a checkout record; they are not intended to contain resume text or contact details.</p></section>
    <section><h2>Our AI provider is OpenAI</h2><p>FirstCareerSteps uses the OpenAI API to provide AI writing and career-planning suggestions. When you use an AI feature, information included in that request—such as your draft text, school, interests, activities and relevant profile details—is sent to OpenAI for processing. Do not enter Social Security numbers, account passwords, payment-card numbers, health records or other sensitive information into the writing tools.</p><p>OpenAI states that API data is not used to train its models by default, unless the customer opts into data sharing. Provider retention and processing depend on its <a href="https://developers.openai.com/api/docs/guides/your-data" target="_blank" rel="noopener noreferrer">API data controls</a>; safety logs may be retained, and exceptions can apply. Deleting your FirstCareerSteps account does not promise immediate deletion from a provider&apos;s logs or backups.</p><p>AI suggestions can be inaccurate. You decide what to keep, change, download or share. Saved content is not automatically posted to LinkedIn or sent to employers.</p></section>
    <section><h2>Private by default</h2><p>Your saved student profile and resumes are not available for public browsing. Viewing your content and downloading stored files require your signed-in account. FirstCareerSteps does not provide a public student directory. Authorized staff and service providers may process information when needed to operate, support, secure or administer the service.</p><p>Download a resume when you are ready to send it to someone. A person who receives a downloaded file can keep or forward it, and we cannot revoke copies outside our service. LinkedIn and other sites you choose to use have their own privacy settings and policies.</p></section>
    <section><h2>How we use and disclose information</h2><p>We use information to provide the tools you request, save your work, process payments, communicate about your account, troubleshoot problems, prevent abuse and meet legal obligations. We do not sell student profiles or provide them for targeted advertising.</p><p>Service providers include Supabase for accounts, databases and file storage; Vercel for website hosting; OpenAI for AI features; Stripe for payments; and Resend for service emails where enabled. An optional YouTube demonstration video connects to YouTube when opened. These providers receive information needed for their respective functions. We may also disclose information when required by law, to protect rights and safety, or as part of a business transfer subject to appropriate protections.</p></section>
    <section><h2>Your choices and account deletion</h2><p>You can review and edit profile content in your account and download your resume. To delete your account, open <Link href="/dashboard/settings">Account Settings</Link>, type DELETE, and confirm. For security, deletion requires a recent sign-in. The process cancels future FirstCareerSteps subscription renewals, removes stored account files, and deletes your sign-in identity and associated saved profile, resumes, experiences, certifications and generated career content.</p><p>Keep any downloads you need before deleting. Deletion cannot be undone. If a provider is unavailable, we will show an error rather than report a deletion as complete. Some earlier cleanup or cancellation may already have occurred; retry or contact us for help.</p></section>
    <section><h2>Retention, security and location</h2><p>We retain account content to provide the service until you delete it or your account, subject to necessary operational and legal retention. Payment processors may retain transaction records for legal, tax, fraud-prevention or dispute purposes. Limited security logs, correspondence and backup copies may remain for their applicable retention periods; backups are not used to republish deleted profiles. We cannot remove information you have independently shared with third parties.</p><p>Information is processed using U.S.-hosted services and may also be processed where our providers operate. We use authentication and access restrictions to protect account information, but no system can guarantee absolute security.</p></section>
    <section><h2>Students, parents and schools</h2><p>The service is intended for students and first-time job seekers aged 13 or older, or the higher minimum age required where they live. Users under 18 need permission from a parent or legal guardian. We do not offer accounts for children under 13. A parent or guardian who believes a younger child has provided information should contact us so we can investigate and remove it as appropriate.</p><p>Schools and educators should assess the service and obtain required approvals before directing students to use it. Do not upload confidential education records or information about other students. An individual account does not automatically give a school or counselor access to its content.</p></section>
    <section><h2>Changes and privacy rights</h2><p>Applicable privacy rights can depend on where you live. Contact us to request access, correction, deletion or other rights that apply to you. We may retain information when law permits or requires it. We will update the effective date when this policy changes and provide additional notice of material changes where required. See our <Link href="/terms">Terms of Service</Link> for the rules for using FirstCareerSteps.</p></section>
  </LegalLayout>;
}
